### ISSUE TITLE
Stretch Goal - Grade Tracking

### ISSUE THREAD

**Issue by BenJarrett** [nss-evening-cohort-14/clown-college-dashboard-clown-college-dashboard#22]
- [ ] As a user, I should be able to track the grades of each student
- [ ] As a user, I should be able to assign a grade to a student when viewing the class
- [ ] As a user, I should be able to view the grades of the students when viewing the Class
